name: Create release
description: Create GitHub release

inputs:
  version:
    description: 'Version to release'
    required: true
  branch:
    description: 'The branch to create a release from'
    required: true
    default: 'main'

runs: 
  using: composite
  steps:
    - name: Create Release
      shell: bash
      run: gh release create ${{ inputs.version }} --target ${{ inputs.branch }} --generate-notes
      env:
        GITHUB_TOKEN: ${{ github.token }}
