name: E2E test
description: Run e2e tests with cypress

runs:
  using: composite
  steps:
    - name: Install dependencies
      uses: ./.github/actions/install
    
    - name: Run e2e tests
      id: run-e2e
      shell: bash
      run: yarn e2e
    
    - name: Upload test results
      uses: dorny/test-reporter@v1
      if: failure() || success()
      with:
        name: e2e test report
        path: test-reports/**/*.xml
        reporter: jest-junit