name: Create release branch
description: Create a release branch

inputs:
  version:
    description: 'Version to release'
    required: true

runs: 
  using: composite
  steps:
    - name: Verify version name
      shell: bash
      run: |
        if [[ ! ${{ inputs.version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version format. Please use semver format (e.g. 1.2.3)"
          exit 1
        fi
