name: Create Pull Request
description: Create a pull request

inputs:
  version: 
    description: 'Version to release'
    required: true
  releaseBranch:
    description: 'The release branch to create a pull request from'
    required: true

runs: 
  using: composite
  steps:
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        branch: ${{ inputs.releaseBranch }}
        base: main
        title: "Release v${{ inputs.version }}"