name: E2E

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: e2e
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        uses: ./.github/actions/build
        with:
          name: e2e

      - name: Deploy Stack
        uses: ./.github/actions/deploy
        with:
          environment: e2e
          build-name: e2e
          aws-account-id: ${{ vars.AWS_ACCOUNT_ID }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Integration test
        uses: ./.github/actions/integration-test
      
      - name: E2E test
        uses: ./.github/actions/e2e-test

      - name: Destroy Stack
        uses: ./.github/actions/destroy
        with:
          environment: e2e
          aws-account-id: ${{ vars.AWS_ACCOUNT_ID }}
          aws-region: ${{ vars.AWS_REGION }}
