name: Release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:  
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test
        uses: ./.github/actions/unit-test
  
  test:
    uses: ./.github/workflows/test.yaml
    needs: [test]
  
  e2e:
    uses: ./.github/workflows/e2e.yaml
    needs: [test]
  
  staging:
    uses: ./.github/workflows/staging.yaml
    needs: [test, deploy-test, execute-e2e]