name: Release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    uses: ./.github/workflows/test.yaml
  
  e2e:
    uses: ./.github/workflows/e2e.yaml
    needs: [release]
  
  staging:
    uses: ./.github/workflows/staging.yaml
    needs: [release, test, e2e]