name: Release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test
        uses: ./.github/actions/unit-test
  
  deploy-test:
    uses: ./.github/workflows/test.yaml
  
  execute-e2e:
    uses: ./.github/workflows/e2e.yaml
  
  deploy-staging:
    uses: ./.github/workflows/staging.yaml
