name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version to release'
        required: true

permissions: write-all

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create
      uses: ./.github/actions/release
      with:
        version: ${{ inputs.version }}
