name: Staging

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        uses: ./.github/actions/build
        with:
          name: staging
  
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Stack
        uses: ./.github/actions/deploy
        with:
          environment: staging
          build-name: staging
          aws-account-id: ${{ vars.AWS_ACCOUNT_ID }}
          aws-region: ${{ vars.AWS_REGION }}
