name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test
        uses: ./.github/actions/unit-test
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        uses: ./.github/actions/build
        with:
          name: test
  
  deploy-test:
    runs-on: ubuntu-latest
    environment: test
    needs: [test, build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Stack
        uses: ./.github/actions/deploy
        with:
          environment: test
          build-name: test
          aws-account-id: ${{ vars.AWS_ACCOUNT_ID }}
          aws-region: ${{ vars.AWS_REGION }}
  
  e2e:
    uses: ./.github/workflows/e2e.yaml
    needs: [deploy-test]
  
  staging:
    uses: ./.github/workflows/staging.yaml
    needs: [e2e]
