name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:  
  deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test
        uses: ./.github/actions/unit-test

      - name: Build
        uses: ./.github/actions/build
        with:
          name: test
    
      - name: Deploy Stack
        uses: ./.github/actions/deploy
        with:
          environment: test
          build-name: test
          aws-account-id: ${{ vars.AWS_ACCOUNT_ID }}
          aws-region: ${{ vars.AWS_REGION }}
  
  e2e:
    uses: ./.github/workflows/e2e.yaml
  
  staging:
    uses: ./.github/workflows/staging.yaml
