name: Deploy to test

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  actions: read
  checks: write

jobs:  
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
        with:
          name: test
    
      - name: Deploy Stack
        uses: ./.github/actions/deploy
        with:
          environment: test
          build-name: test
          aws-account-id: ${{ vars.AWS_ACCOUNT_ID }}
          aws-region: ${{ vars.AWS_REGION }}
